### PR TITLE
add a context to OpenStream and NewStream

### LINKED ISSUE #86: OpenStream needs to take a context
This could block on some systems that restrict the number of open streams.

### PR DESCRIPTION
**Pull request by marten-seemann**
Fixes #86, using option 1.

Associated PRs (These PRs will all need to be rebased after we've merged this PR and cut a new release):

- https://github.com/libp2p/go-libp2p-swarm/pull/232
- https://github.com/libp2p/go-libp2p/pull/1033
- https://github.com/libp2p/go-libp2p-kad-dht/pull/701
- https://github.com/libp2p/go-libp2p-transport-upgrader/pull/70
- https://github.com/libp2p/go-libp2p-testing/pull/31
- https://github.com/libp2p/go-ws-transport/pull/98
- https://github.com/libp2p/go-libp2p-quic-transport/pull/189
- https://github.com/libp2p/go-libp2p-yamux/pull/29
- https://github.com/libp2p/go-libp2p-mplex/pull/21
- https://github.com/libp2p/go-libp2p-webrtc-direct/pull/35

### CODE REVIEW

**Comment by marten-seemann** [comment]
CI is failing because this is a breaking API change. Obviously it is...

**Review by Stebalien — APPROVED** [review]
LGTM once we have all the related PRs in place.

**Comment by Stebalien** [comment]
All the transport PRs LGTM as well. @raulk can we get a final signoff on the change? This should have minimal to no impact on downstream users (unless they explicitly try to create a new stream on a _specific_ connection, but most users just call `host.NewStream(...)`.

**Review by raulk — APPROVED** [review]

**Comment by raulk** [comment]
@marten-seemann could you please announce the upcoming change in discuss.libp2p.io?

**Comment by marten-seemann** [comment]
> @marten-seemann could you please announce the upcoming change in discuss.libp2p.io?

Should we do that when we actually cut a release of go-libp2p?

Status of the merge:
All PRs merged, expect for https://github.com/libp2p/go-libp2p-webrtc-direct/pull/35 (build is broken, repo doesn't seem to be maintained) and https://github.com/libp2p/go-libp2p-kad-dht/pull/701 (depends on go-libp2p).
We might want to make sure that go-yamux and go-mplex respect the context before actually cutting a new release of go-libp2p (with the current changes, they just conform to the new interface but ignore the context). Still waiting for PRs to get reviewed on the respected repos.

**Pull request merged**
