### PR TITLE
Remove btcsuite/btcd dep

### PR DESCRIPTION
**Pull request by MarcoPolo**
I don't think need to pull in this btcd dependency. btcec is now it's own module.

This will also prevent us from forcing the btcd dep upgrade on downstream users. It breaks somethings especially https://github.com/whyrusleeping/ledger-filecoin-go which is used by lotus.

### CODE REVIEW

**Comment by marten-seemann** [comment]
Will we run into the problem fixed in https://github.com/libp2p/go-libp2p-core/pull/254 again?

My conclusion back then was that this will have to wait until we stop using Go 1.17.

**Comment by MarcoPolo** [comment]
go checks pass, so maybe not?

I think removing this dep would side step that problem by not having btcd to conflict with.

**Comment by MarcoPolo** [comment]
Was able to sucessfully remove this dep from go-libp2p as well which unblocked lotus from being able to update: https://github.com/filecoin-project/lotus/pull/8970

**Comment by marten-seemann** [comment]
> go checks pass, so maybe not?

The checks passed in this repo, but not when updating go-libp2p to the new version. I'm ok with merging this (actually, I'd be very happy to get rid of this hack!!), but we should make sure that go-libp2p will still pass CI when we make this change.
More details in https://github.com/libp2p/go-libp2p-core/issues/252.

**Comment by MarcoPolo** [comment]
> The checks passed in this repo, but not when updating go-libp2p to the new version.

Seems like the tests are passing in go-libp2p too: https://github.com/libp2p/go-libp2p/pull/1641

**Review by marten-seemann — APPROVED** [review]
Then let’s get rid of this hack!

**Pull request merged**
